version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing frontend dependencies..."
      - npm install
      - echo "Installing backend dependencies..."
      - (cd lambda-functions && npm install)

  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Building backend..."
      - (cd lambda-functions && npm run build)

  post_build:
    commands:
      - echo "Build finished on `date`"
      - echo "Packaging SAM application..."
      - sam package --template-file template.yml --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged-template.yml
      - echo "Deploying SAM application..."
      - aws cloudformation deploy --template-file packaged-template.yml --stack-name short-url-slinger-stack --capabilities CAPABILITY_IAM
      - echo "Syncing frontend to S3..."
      - aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete

artifacts:
  files:
    # Frontend application
    - 'dist/**/*'
    # Backend Lambda functions
    - 'lambda-functions/dist/**/*'
    # Packaged template file
    - packaged-template.yml
  base-directory: .

cache:
  paths:
    - node_modules/**/*
    # Add path to backend node_modules to cache them as well
    - lambda-functions/node_modules/**/*
