# This file defines the Lambda function resources and their triggers.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function resources for the short-url-slinger application.

Parameters:
  UrlMappingsTableName:
    Type: String
    Description: The name of the DynamoDB table for URL mappings.
  ShortUrlDomain:
    Type: String
    Description: The custom domain for the shortened URLs (e.g., short.ly).
  # This new parameter will receive the ID of the API Gateway from the main stack.
  ShortUrlApiId:
    Type: String
    Description: The ID of the API Gateway to which to attach the functions.

Resources:
  # This is the Lambda function for creating a new short URL.
  CreateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createShortUrl
      CodeUri: ../lambda-functions/
      Handler: dist/createShortUrl/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          URL_MAPPINGS_TABLE: !Ref UrlMappingsTableName
          SHORT_URL_DOMAIN: !Ref ShortUrlDomain
      # This policy grants the function permission to write to the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlMappingsTableName
      Events:
        # This event mapping links the function to the POST /create endpoint.
        CreateShortUrlApiEvent:
          Type: Api
          Properties:
            Path: /create
            Method: post
            RestApiId: !Ref ShortUrlApiId # Use the parameter here

  # This is the Lambda function for redirecting a short URL to the original long URL.
  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: redirectUrl
      CodeUri: ../lambda-functions/
      Handler: dist/redirectUrl/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          URL_MAPPINGS_TABLE: !Ref UrlMappingsTableName
      # This policy grants the function permission to read from and update the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlMappingsTableName
      Events:
        # This event mapping links the function to the GET /{shortCode} endpoint.
        RedirectUrlApiEvent:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: get
            RestApiId: !Ref ShortUrlApiId # Use the parameter here
