AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Short URL Slinger - Serverless URL shortening service

Parameters:
  ShortUrlDomain:
    Type: String
    Description: The custom domain for the shortened URLs (e.g., short.ly).
    Default: "short.ly"

Globals:
  Api:
    Cors:
      AllowMethods: "'POST, GET, OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB Table
  UrlMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlMappings
      AttributeDefinitions:
        - AttributeName: "shortCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "shortCode"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  # Lambda Functions
  CreateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createShortUrl
      CodeUri: ../lambda-functions/
      Handler: dist/createShortUrl/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          URL_MAPPINGS_TABLE: !Ref UrlMappingsTable
          SHORT_URL_DOMAIN: !Ref ShortUrlDomain
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlMappingsTable
      Events:
        CreateShortUrlApiEvent:
          Type: Api
          Properties:
            Path: /create
            Method: post

  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: redirectUrl
      CodeUri: ../lambda-functions/
      Handler: dist/redirectUrl/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          URL_MAPPINGS_TABLE: !Ref UrlMappingsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlMappingsTable
      Events:
        RedirectUrlApiEvent:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: get

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiId:
    Description: "API Gateway ID"
    Value: !Ref ServerlessRestApi
